name : reaction-time
game_class : ReactionTimeGame
author: MKR
version: 1.0
tags:
  - visual
  - attention
locales:
  - en:
    - title:        Reaction Time Test
    - subtitle:
    - description:
    - instructions: Click the targets immediately after they appear.
  - cz:
    - title:        Reakční test
    - subtitle:
    - description:
    - instructions: Strefte se do cíle co nejrychleji poté, co se objeví.
scripts:
styles:
resources:
settings:
gamepacks:
    - name : default
      locales:
        - en:
        - cz:
