name : colortest-reverse
game_class : ReverseColorTestGame
author: MKR
version: 1.0
tags:
  - visual
scripts:
styles:
resources:
settings:
locales:
  - en:
    - title: Reverse Color Test
gamepacks:
    - name : default
      settings:
      resources:
      locales:
        - en:
