name : memory-game
game_class : MemoryGame
author: MKR
version: 1.0
tags:
  - visual
  - memory
  - entertainment
scripts:
styles:
resources:
settings:
locales:
  - en:
    - title: Memory Game
    - subtitle: " "
    - description: " "
    - instructions: " "
  - cz:
    - title: Pexeso
    - subtitle: " "
    - description: " "
    - instructions: " "
gamepacks:
    - name : default
      locales:
        - en:
        - cz:
      resources:
        - tileset:  tileset.json
    - name : animals
      locales:
        - en:
        - cz:
      resources:
        - tileset:  tileset.json
    - name : sports
      locales:
        - en:
        - cz:
      resources:
        - tileset:  tileset.json
