name : sudoku
game_class : SudokuGame
author: MKR
version: 1.0
tags:
  - entertainment
locales:
  - en:
    - title:        Sudoku
    - subtitle:
    - description:
    - instructions:
  - cz:
    - title:        Sudoku
    - subtitle:
    - description:
    - instructions:
scripts:
  - sudoku.js
styles:
  - sudoku.css
resources:
settings:
gamepacks:
    - name : default
      locales:
        - en:
          - title: Sudoku
        - cz:
          - title: Sudoku
