name : single-n-back
game_class : NBackSingleGame
author: MKR
version: 1.0
tags:
  - visual
  - memory
  - attention
locales:
  - en:
    - title:        Single N-Back
    - subtitle:     Challenge your working memory
    - description:  The n-back task is a continuous performance task that is commonly used as an assessment in cognitive neuroscience to measure a part of working memory and working memory capacity. The subject is presented with a sequence of stimuli, and the task consists of indicating when the current stimulus matches the one from n steps earlier in the sequence. The load factor n can be adjusted to make the task more or less difficult.
    - instructions: When the game starts, you will see a blue box placed at one of 9 possible positions in a 3x3 grid. Remember where the box appeared. After a few seconds, another box appears in a different position. The task is, to recall if the currently shown box is at the same position as the box shown N frames back (N times ago). If you think the current box has the same position as the box shown N frames earlier, press the Position button. Start with N=2 (2-back), and eventually you will be good enough to try 3-back, 4-back and so on.
scripts:
styles:
resources:
settings:
gamepacks:
    - name : default
      locales:
        - en:
