[
        { 
            "name": "N",
            "title": "",
            "description": "",
            "type": "int",
            "minValue": 1,
            "maxValue": 3,
            "default": 2
        },
        { 
            "name": "L",
            "title": "",
            "description": "",
            "type": "int",
            "minValue": 5,
            "maxValue": 50,
            "default": 10
        },
        { 
            "name": "delay",
            "title": "",
            "description": "",
            "type": "int",
            "minValue": 500,
            "maxValue": 10000,
            "by": 100,
            "default": 2000 
        },
        { 
            "name": "dualType",
            "title": "",
            "description": "",
            "type": "string",
            "values": [
                "colors",
                "signs"
            ],
            "valueLabels": [
                "Colors",
                "Signs"
            ],
            "default": "signs"
        },
        { 
            "name": "nColors",
            "title": "",
            "description": "",
            "type": "int",
            "minValue": 1,
            "maxValue": 8,
            "default": 4
        },
        { 
            "name": "nSigns",
            "title": "",
            "description": "",
            "type": "int",
            "minValue": 1,
            "maxValue": 8,
            "default": 5
        }
]               