name : fifteen
game_class : Fifteen
author: MKR
version: 1.0
tags:
  - entertainment
locales:
  - en:
    - title:        Fifteen
    - subtitle:     " "
    - description:  " "
    - instructions: " "
  - cz:
    - title:        Patnáctka
    - subtitle:     " "
    - description:  " "
    - instructions: " "
scripts:
styles:
resources:
    - tileset:  tileset.json
settings:
gamepacks:
    - name : default
      locales:
        - en:
          - title: Fifteen
        - cz:
          - title: Patnáctka
